name: anyfeast_assignment
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  avatar_glow: ^3.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_svg: ^2.2.3
  google_fonts: ^8.0.0
  shared_preferences: ^2.5.4
  smooth_page_indicator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_logo.png"
    background_color: "#A0130E"
    theme_color: "#A0130E"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
